### ISSUE TITLE
xarray-datatree 0.0.14 failure with xarray=2024.10.0

### ISSUE THREAD

**Issue by akrherz** [conda-forge/xarray-datatree-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Current versions of `xarray-datatree` and `xarray` seem to not be compatible.

```
$ python -c "import datatree"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/prod/lib/python3.11/site-packages/datatree/__init__.py", line 2, in <module>
    from .datatree import DataTree
  File "/opt/miniconda3/envs/prod/lib/python3.11/site-packages/datatree/datatree.py", line 33, in <module>
    from xarray.core.utils import (
ImportError: cannot import name 'HybridMappingProxy' from 'xarray.core.utils' (/opt/miniconda3/envs/prod/lib/python3.11/site-packages/xarray/core/utils.py)
```

[this package was merged into xarray 2024.10.0 ?](https://github.com/pydata/xarray/issues/8572)

### Installed packages

# packages in environment at /opt/miniconda3/envs/prod:
#
# Name                    Version                   Build  Channel
..snipped as too large for github form :( ...
xarray                    2024.10.0          pyhd8ed1ab_0    conda-forge
xarray-datatree           0.0.14             pyhd8ed1ab_0    conda-forge

### Environment info

     active environment : prod
    active env location : /opt/miniconda3/envs/prod
            shell level : 7
       user config file : /home/akrherz/.condarc
 populated config files : /home/akrherz/.condarc
          conda version : 24.9.2
    conda-build version : 24.9.0
         python version : 3.11.10.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.9.2=0
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/akrherz/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/akrherz/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.11.10 Linux/5.14.0-427.40.1.el9_4.x86_64 rocky/9.4 glibc/2.34 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.10
                UID:GID : 43306:101
             netrc file : /home/akrherz/.netrc
           offline mode : False

**Comment by nhj4064** [comment]
Were you able to resolve this issue?

**Comment by andersy005** [comment]
As of Dec 2024, you no longer need to install xarray-datatree separately—it's now bundled with xarray. https://xarray.dev/blog/datatree
